---
apiVersion: v1
kind: Secret
metadata:
  name: bmh-secret
type: Opaque
data:
  password: '{{fromSecret "policies" "bmh-secret" "password"}}'
  username: '{{fromSecret "policies" "bmh-secret" "username"}}'
