---
apiVersion: v1
kind: Secret
metadata:
  name: pull-secret-workload-clusters
type: Opaque
data:
  .dockerconfigjson: '{{ (fromSecret "policies" "pull-secret-workload-clusters" ".dockerconfigjson" ) }}'
