---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: odf-operator
  namespace: openshift-storage
  annotations:
spec:
  installPlanApproval: Manual
  name: odf-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
status:
  state: AtLatestKnown
