kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: noobaa-core
  namespace: openshift-storage
status:
  availableReplicas: 1
  readyReplicas: 1
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: noobaa-db-pg
  namespace: openshift-storage
status:
  availableReplicas: 1
  readyReplicas: 1
---
apiVersion: noobaa.io/v1alpha1
kind: BackingStore
metadata:
  name: noobaa-default-backing-store
  namespace: openshift-storage
status:
  phase: Ready