apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virt-network-provisioner
rules:
- apiGroups: ["k8s.cni.cncf.io"]
  resources: ["network-attachment-definitions"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]