---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops-operator
  namespace: openshift-gitops-operator
  labels:
    operators.coreos.com/openshift-gitops-operator.openshift-operators: ''
spec:
  channel: placeholder # overwritten by inline patch within PolicyGenerator
  installPlanApproval: Manual
  name: openshift-gitops-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  config:
    resources:
      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 1Gi
    env:
    - name: DISABLE_DEFAULT_ARGOCD_INSTANCE
      value: "true"
    - name: ARGOCD_CLUSTER_CONFIG_NAMESPACES
      #these are namespaces in which you install argocd, those instances can then have namespaces: All Namespaces to allow deployment to any namespace.
      value: openshift-gitops,ztp-gitops,open-cluster-management-global-set,policies,rhacm_policies
status:
  state: AtLatestKnown
  # installedCSV: openshift-gitops-operator.v1.10.2
