apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-manager
  namespace: multicluster-engine
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicluster-engine-operator
  namespace: multicluster-engine
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: hypershift
spec:
  replicas: 0
