---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sg-example-group
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-reader
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: sg-example-group
---
# Example Org Security Team, cluster-reader and ability to run ACS
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sg-example-group
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-reader
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: sg-example-group
---
# Example Org Management Team, cluster-viewer
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sg-example-cluster-admins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-reader
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: sg-example-cluster-admins