apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rov-admin-breakglass
  annotations:
    description: "Breakglass cluster-admin access rov-admin"
subjects:
- kind: User
  name: rov-admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
