---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - ./policyGenerator-hub-lab-config.yaml
  - ./policyGenerator-hub-production-config.yaml
  - ./policyGenerator-all-clusters.yaml
  - ./policyGenerator-group-virt-base.yaml
  - ./policyGenerator-group-virt-config.yaml
  - ./policyGenerator-group-virt-oneshot.yaml
  - ./policyGenerator-site-example.yaml

commonAnnotations:
  argocd.argoproj.io/compare-options: IgnoreExtraneous
