apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: ztp-secrets
placementBindingDefaults:
  name: binding-ztp-secrets
policyDefaults:
  namespace: policies
  categories:
    - SC System and Communications Protection
  controls:
    - SC-28 Protection Of Information At Rest
  standards:
    - NIST SP 800-53
  remediationAction: enforce
  consolidateManifests: false
  orderManifests: false
policies:

# Distribute ZTP secrets to cluster namespaces - Start
  - name: policy-hub-secrets-ztp
    namespaceSelector:
      matchExpressions:
        - {key: cluster.open-cluster-management.io/managedCluster, operator: Exists}
    manifests:
      - path: ztp-secrets/bmh-secret.yaml
      - path: ztp-secrets/pull-secret.yaml
      - path: ztp-secrets/pull-secret-workload-clusters.yaml
    policySets:
      - policyset-hub-cluster-secrets
# Distribute ZTP secrets to cluster namespaces - End

policySets:
  - name: policyset-hub-cluster-secrets
    placement:
      placementName: placement-hub-clusters
