---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: hub-lab-ztp-source-secrets
placementBindingDefaults:
  name: binding-hub-lab-ztp-source-secrets
policyDefaults:
  namespace: policies
  categories:
    - SC System and Communications Protection
  controls:
    - SC-28 Protection Of Information At Rest
  standards:
    - NIST SP 800-53
  remediationAction: enforce
  consolidateManifests: false
  orderManifests: false
  policySets:
    - policyset-hub-lab-ztp-source-secrets
policies:
  - name: policy-hub-lab-ztp-source-secrets
    manifests:
      - path: lab-ztp-secrets-source/pull-secret-from-cluster.yaml
      - path: lab-ztp-secrets-source/pull-secret-workload-clusters-from-cluster.yaml
      - path: lab-ztp-secrets-source/bmh-secret-sushy-lab.yaml

policySets:
  - name: policyset-hub-lab-ztp-source-secrets
    placement:
      placementName: placement-hub-lab-clusters
