---
apiVersion: v1
kind: Secret
metadata:
  name: dynakube
  namespace: openshift-logging
type: Opaque
data:
  apiToken: '{{hub fromSecret "" "dynakube" "apiToken" hub}}'
  dataIngestToken: '{{hub fromSecret "" "dynakube" "dataIngestToken" hub}}'
