---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: metallb-operator-sub
  namespace: metallb-system
  annotations:
spec:
  channel: placeholder # overwritten by inline patch within PolicyGenerator
  installPlanApproval: Manual
  name: metallb-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
status:
  state: AtLatestKnown
  #installedCSV: metallb-operator.4.12.0-202312061330
