apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
  name: agent
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  databaseStorage:
    #storageClassName: ocs-storagecluster-ceph-rbd  #Using Default
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  filesystemStorage:
    #storageClassName: ocs-storagecluster-ceph-rbd #Using Default
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 100Gi
  imageStorage:
    #storageClassName: ocs-storagecluster-ceph-rbd #Using Default
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
  osImages:
    - openshiftVersion: "4.18"
      url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.18/4.18.1/rhcos-4.18.1-x86_64-live.x86_64.iso"
      rootFSUrl: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.18/4.18.1/rhcos-4.18.1-x86_64-live-rootfs.x86_64.img"
      cpuArchitecture: "x86_64"
      version: "418.94.202503061016-0"
    - openshiftVersion: "4.19"
      version: "9.6.20250523-0" # The specific RHCOS version string
      url: "https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.19/4.19.0/rhcos-4.19.0-x86_64-live-iso.x86_64.iso"
      cpuArchitecture: "x86_64"
    - openshiftVersion: "4.20"
      url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.20/4.20.0/rhcos-4.20.0-x86_64-live-iso.x86_64.iso"
      rootFSUrl: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.20/4.20.0/rhcos-4.20.0-x86_64-live-rootfs.x86_64.img"
      cpuArchitecture: "x86_64"
      version: "420.96.20251027-0"
    
