apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
  name: agent
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  databaseStorage:
    #storageClassName: lvms-vg1-lvms  # hub-lab PolicyGenerator patches AgentServiceConfig to set this
    #storageClassName: ocs-storagecluster-ceph-rbd  #Using Default
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  filesystemStorage:
    #storageClassName: lvms-vg1-lvms  # hub-lab PolicyGenerator patches AgentServiceConfig to set this
    #storageClassName: ocs-storagecluster-ceph-rbd #Using Default
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 100Gi
  imageStorage:
    #storageClassName: lvms-vg1-lvms  # hub-lab PolicyGenerator patches AgentServiceConfig to set this
    #storageClassName: ocs-storagecluster-ceph-rbd #Using Default
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
  osImages:
    - openshiftVersion: "4.20"
      url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.20/4.20.0/rhcos-4.20.0-x86_64-live-iso.x86_64.iso"
      rootFSUrl: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.20/4.20.0/rhcos-4.20.0-x86_64-live-rootfs.x86_64.img"
      cpuArchitecture: "x86_64"
      version: "420.96.20251027-0"
## To add newer versions we recommend adding a spec override in the policyGenerator-hub-lab-config.yaml file

