---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-all-managed-clusters
  namespace: policies
spec:
  tolerations:
  - key: cluster.open-cluster-management.io/unavailable
    operator: Exists
  - key: cluster.open-cluster-management.io/unreachable
    operator: Exists
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - {key: common, operator: In, values: ["true"]}
            - {key: name, operator: NotIn, values: ["local-cluster"]}
