apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-hub-clusters-oneshot
  namespace: policies
spec:
  tolerations:
  - key: cluster.open-cluster-management.io/unavailable
    operator: Exists
  - key: cluster.open-cluster-management.io/unreachable
    operator: Exists
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
            - {key: name, operator: In, values: ["local-cluster"]}
            - {key: ztp-done, operator: DoesNotExist}
