# NOTE: the {{` and `}} at the start and end of are is used to escape
# Go templating applied by ACM from interpreting double braces, i.e
# {{ }}.
apiVersion: v1
data:
  backup.sh:  |
    {{`
    #!/bin/bash

    env |grep -i nfs
    # - select master nodes with Ready status only
    # - of those, sort randomly and select the first
    oc get node -l node-role.kubernetes.io/master -o go-template='{{range $node := .items}}{{range $condition := $node.status.conditions}}{{if eq $condition.type "Ready"}}node/{{$node.metadata.name}}{{"\n"}}{{end}}{{end}}{{end}}' | sort -R | head -n 1 | xargs -I {} --  oc debug -n ocpadmin-etcd-backup {} -- chroot /host env NFS_SERVER=$NFS_SERVER NFS_SHARE_NAME=$NFS_SHARE_NAME CLUSTER_NAME=$CLUSTER_NAME bash  -c 'cat << EOF |bash
    export BACKUP_DIR=/mnt/nfs/\${CLUSTER_NAME}

    echo "Backing up etcd to nfs"
    mkdir -p /mnt/nfs
    mount -t nfs \$NFS_SERVER:$NFS_SHARE_NAME /mnt/nfs || exit 1
    echo creating directory \${CLUSTER_NAME}
    mkdir -p \$BACKUP_DIR
    echo running command: /usr/local/bin/cluster-backup.sh \$BACKUP_DIR
    /usr/local/bin/cluster-backup.sh \$BACKUP_DIR
    echo running command: find \$BACKUP_DIR -type f -mtime +"7" -delete
    find \$BACKUP_DIR -type f -mtime +"7" -delete

    umount /mnt/nfs
    rm -fr /mnt/nfs
    EOF
    '
    `}}
kind: ConfigMap
metadata:
  name: etcd-backup-script
  namespace: ocpadmin-etcd-backup
