---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: Openshift Backup Automation Tool
    openshift.io/display-name: Backup ETCD Automation
  name: ocpadmin-etcd-backup
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: openshift-backup
  namespace: ocpadmin-etcd-backup
  labels:
    app: openshift-backup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-etcd-backup
rules:
  - apiGroups:
      - ''
    resources:
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - ''
    resources:
      - pods
      - pods/log
      - namespaces
    verbs:
      - get
      - list
      - create
      - delete
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-backup
  labels:
    app: openshift-backup
subjects:
  - kind: ServiceAccount
    name: openshift-backup
    namespace: ocpadmin-etcd-backup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-etcd-backup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openshift-backup-privileged
  namespace: ocpadmin-etcd-backup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
  - kind: ServiceAccount
    name: openshift-backup
    namespace: ocpadmin-etcd-backup
---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: openshift-backup
  namespace: ocpadmin-etcd-backup
  labels:
    app: openshift-backup
spec:
  schedule: 15 3 * * *
  timeZone: "Pacific/Auckland"
  #schedule: CRON_TZ=Pacific/Auckland 15 3 * * *
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    metadata:
      labels:
        app: openshift-backup
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: openshift-backup
        spec:
          containers:
            - name: backup
              image: registry.redhat.io/openshift4/ose-cli:latest
              env:
              - name: NFS_SERVER
                value: '{{ fromConfigMap "openshift-config" "cluster-info" "nfs_server" }}'
              - name: NFS_SHARE_NAME
                value: '{{ fromConfigMap "openshift-config" "cluster-info" "nfs_share" }}'
              - name: CLUSTER_NAME
                value: '{{ if eq (fromClusterClaim "name") "local-cluster" }}{{ fromConfigMap "openshift-config" "cluster-info" "cluster_name" }}{{ else }}{{ fromClusterClaim "name"}}{{ end }}'
              command: ["bash", "/scripts/backup.sh" ]
              resources:
                limits:
                  cpu: 200m
                  memory: 128Mi
                requests:
                  cpu: 50m
                  memory: 32Mi
              volumeMounts:
              - mountPath: /scripts
                name: scripts
          restartPolicy: Never
          volumes:
          - name: scripts
            configMap:
              name: etcd-backup-script
          terminationGracePeriodSeconds: 30
          activeDeadlineSeconds: 500
          dnsPolicy: ClusterFirst
          serviceAccountName: openshift-backup
          serviceAccount: openshift-backup

