apiVersion: v1
kind: ServiceAccount
metadata:
  name: acs-central-jobs
  namespace: stackrox
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: acs-central-jobs
  namespace: stackrox
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - create
  - patch
  - update
- apiGroups:
  - platform.stackrox.io
  resources:
  - securedclusters
  verbs:
  - get
  - list
  - patch
  - update
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: acs-central-jobs
  namespace: stackrox
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: acs-central-jobs
subjects:
- kind: ServiceAccount
  name: acs-central-jobs
  namespace: stackrox
