apiVersion: platform.stackrox.io/v1alpha1
kind: Central
metadata:
  namespace: stackrox
  name: stackrox-central-services
spec:
  central:
    db:
      persistence:
        persistentVolumeClaim:
          claimName: central-db
          storageClassName: ocs-storagecluster-ceph-rbd
      resources:
        requests:
          cpu: '500m'
          memory: '2Gi'
    declarativeConfiguration:
      configMaps:
        - name: acs-configuration
    resources:
      limits:
        cpu: 1000m
        memory: 4Gi
      requests:
        cpu: 15m
        memory: 768Mi
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
    exposure:
      loadBalancer:
        enabled: false
        port: 443
      nodePort:
        enabled: false
      route:
        enabled: true
  egress:
    connectivityPolicy: Online
  scanner:
    db:
      resources:
        requests:
          memory: 1536Mi
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
    analyzer:
      resources:
        limits:
          cpu: 500m
          memory: 1024Mi
        requests:
          cpu: 25m
          memory: 512Mi
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      scaling:
        autoScaling: Enabled
        maxReplicas: 5
        minReplicas: 2
        replicas: 2
    scannerComponent: Enabled
  overlays:
  - apiVersion: apps/v1
    kind: Deployment
    name: central
    patches:
      ## IMPORTANT NOTE - THE FOLLOWING PATCH IS REQUIRED WHEN USING AN INTERNAL QUAY REGISTRY ##
      ## IMPORTANT NOTE - REMOVING THIS CONFIGURATION WILL BREAK CLUSTER TO QUAY INTEGRATION ##
    - path: spec.template.spec.containers[name:central].env[-1]
      value: |
        name: ROX_DISABLE_AUTOGENERATED_REGISTRIES
        value: "true"
      ## IMPORTANT NOTE - SEE ABOVE ##
---
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: acs
spec:
  applicationMenu:
    section: Red Hat applications
    imageURL: 'https://{{ (lookup "route.openshift.io/v1" "Route" "openshift-console" "console" ).spec.host }}/static/assets/openshift.svg'
  href: https://{{ (lookup "route.openshift.io/v1" "Route" "stackrox" "central").spec.host }}
  location: ApplicationMenu
  text: 'Red Hat Advanced Cluster Security for Kubernetes'
