apiVersion: batch/v1
kind: Job
metadata:
  name: create-integrations
  namespace: stackrox
spec:
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - |
          #!/usr/bin/env bash

            # Wait for central to be ready
            attempt_counter=0
            max_attempts=20
            echo "Waiting for central to be available..."
            until $(curl -k --output /dev/null --silent --head --fail https://central); do
                if [ ${attempt_counter} -eq ${max_attempts} ];then
                  echo "Max attempts reached"
                  exit 1
                fi

                printf '.'
                attempt_counter=$(($attempt_counter+1))
                echo "Made attempt $attempt_counter, waiting..."
                sleep 30
            done

            echo "Performing Initial ACS Configuration"
            curl -k -X POST -H "Content-Type: application/json" -u "admin:$PASSWORD" https://central/v1/imageintegrations \
            -d '{"name":"local-quay","type":"quay","categories":["REGISTRY","SCANNER"],"quay":{"endpoint":"'$QUAY_URL'","oauthToken":"","insecure":false,"registryRobotCredentials":null},"autogenerated":false,"clusterId":"","skipTestIntegration":true,"source":null}'

          echo "Done"
        env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: central-htpasswd
        - name: QUAY_URL
          value: '{{hub fromConfigMap "" "quay-config" "local" hub}}'
        image: registry.redhat.io/openshift4/ose-cli:latest
        imagePullPolicy: Always
        name: create-acs-integrations
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: acs-central-jobs
      serviceAccountName: acs-central-jobs
      terminationGracePeriodSeconds: 30
