# Apply to Workload clusters only
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    transfered-from-hub: "true"
  namespace: openshift-config
  name: htpass-secret
data:
  htpasswd: '{{hub ((lookup "v1" "Secret" "" (printf "breakglass-admin-%s" .ManagedClusterName )).data.htpasswd) | protect hub}}'