---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-main
  namespace: openshift-monitoring
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
      smtp_from: '{{hub (lookup "v1" "Secret" "" "alertmanager-secrets").data.smtp_from | base64dec | protect hub}}'
      smtp_require_tls: false
      smtp_smarthost: '{{hub (lookup "v1" "Secret" "" "alertmanager-secrets").data.smtp_smarthost| base64dec | protect hub}}'
    inhibit_rules:
      - equal:
          - namespace
          - alertname
        source_matchers:
          - severity = critical
        target_matchers:
          - severity =~ warning|info
      - equal:
          - namespace
          - alertname
        source_matchers:
          - severity = warning
        target_matchers:
          - severity = info
      - equal:
          - namespace
        source_matchers:
          - alertname = InfoInhibitor
        target_matchers:
          - severity = info
    receivers:
      - name: Default
      - name: Watchdog
      - name: Critical
        email_configs:
          - to: '{{hub (lookup "v1" "Secret" "" "alertmanager-secrets").data.email_recipient | base64dec | protect hub}}'
            send_resolved: true
      - name: 'null'
    route:
      group_by:
        - job
      group_interval: 5m
      group_wait: 30s
      receiver: Default
      repeat_interval: 12h
      routes:
        - matchers:
            - alertname = Watchdog
          receiver: Watchdog
        - matchers:
            - alertname = InfoInhibitor
          receiver: 'null'
        - receiver: Critical
          match:
            severity: critical
