apiVersion: hco.kubevirt.io/v1beta1
kind: HyperConverged
metadata:
  labels:
    app: kubevirt-hyperconverged
  name: kubevirt-hyperconverged
  namespace: openshift-cnv
spec:
  vddkInitImage: image-registry.openshift-image-registry.svc:5000/openshift-mtv/vddk:latest
  certConfig:
    ca:
      duration: 48h0m0s
      renewBefore: 24h0m0s
    server:
      duration: 24h0m0s
      renewBefore: 12h0m0s
  enableApplicationAwareQuota: true
  evictionStrategy: LiveMigrate
  featureGates:
    deployKubeSecondaryDNS: false
    disableMDevConfiguration: false
    downwardMetrics: false
    persistentReservation: false
  liveMigrationConfig:
    network: default/livemigration-network #  macvlan NAD on VLAN 3113 via bond0.3113
    allowAutoConverge: false
    allowPostCopy: false
    completionTimeoutPerGiB: 800
    parallelMigrationsPerCluster: 5
    parallelOutboundMigrationsPerNode: 2
    progressTimeout: 150
  resourceRequirements:
    vmiCPUAllocationRatio: 10
  uninstallStrategy: BlockUninstallIfWorkloadsExist
  virtualMachineOptions:
    disableFreePageReporting: false
    disableSerialConsoleLog: true
  workloadUpdateStrategy: 
    batchEvictionInterval: 1m0s
    batchEvictionSize: 10
    workloadUpdateMethods:
    - LiveMigrate
  workloads:
    nodePlacement:
      nodeSelector: {}
